import slide1 from "@/assets/images/BGHERO1.jpg";
import slide2 from "@/assets/images/BGHERO2.jpg";
import slide3 from "@/assets/images/BGHERO3.jpg";
import slide4 from "@/assets/images/BGHERO4.jpg";
import slide5 from "@/assets/images/BGHERO5.jpg";
import slide6 from "@/assets/images/BGHERO6.jpg";
import slide7 from "@/assets/images/BGHERO7.jpg";
import ce1 from "@/assets/perumahan/CarissmaMansion/ce1.jpg";
export const properties = [
  {
    title: "Carissma Mansion - Emerald",
    location: "Jl. Sukabangun II Soak Simpur, Lr. Karya",
    image: slide1,
    description:
      "Perumahan cluster dengan konsep modern minimalis, lingkungan asri dan fasilitas lengkap. Cocok untuk keluarga muda yang mengutamakan kenyamanan dan keamanan.",
    type: "Tipe 70/105",
    landSize: "7x15 m²",
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    price: "Rp 750.000.000",
    dp: "Rp 50.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl:
      "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3984.6471574662787!2d104.7439331!3d-2.9174411!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e3b730051bf72df%3A0x387502bda2091a04!2sCluster%20Carissma%20Mansion!5e0!3m2!1sen!2sid!4v1744256227104!5m2!1sen!2sid",
    facilities: [
      "24 Jam Security",
      "1 Gate System",
      "Area Komersial",
      "Masjid",
      "Parkir Luas",
    ],
    media: [
      { type: "image", url: ce1 },
      { type: "image", url: slide2 },
      { type: "image", url: slide3 },
      { type: "video", url: "https://www.youtube.com/embed/example1" },
    ],
  },
  {
    title: "Carissma Mansion - Ruby",
    location: "Jl. Sukabangun II Soak Simpur, Lr. Karya",
    image: slide2,
    description:
      "Perumahan dengan view pegunungan dan udara segar. Konsep green living dengan banyak area terbuka hijau.",
    type: "Tipe 70",
    landSize: "91 m²",
    bedrooms: 3,
    bathrooms: 1,
    floors: 1,
    price: "Rp 575.000.000",
    dp: "Rp 45.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl:
      "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3984.6471574662787!2d104.7439331!3d-2.9174411!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e3b730051bf72df%3A0x387502bda2091a04!2sCluster%20Carissma%20Mansion!5e0!3m2!1sen!2sid!4v1744256227104!5m2!1sen!2sid",
    facilities: [
      "One-Gate System",
      "Listrik 2200 Watt",
      "PDAM",
      "Fasilitas Umum",
    ],
    media: [
      { type: "image", url: slide2 },
      { type: "image", url: slide3 },
      { type: "video", url: "https://www.youtube.com/embed/example2" },
    ],
  },
  {
    title: "Bukit Indah Lestari",
    location: "Jl. Bukit Indah No. 78, Bogor",
    image: slide3,
    description:
      "Perumahan eksklusif di kawasan sejuk Bogor dengan view kota yang memukau. Fasilitas premium dan lingkungan yang nyaman.",
    type: "Tipe 60/120",
    landSize: "120 m²",
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    price: "Rp 950.000.000",
    dp: "Rp 100.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl: "https://www.google.com/maps/embed?pb=...",
    facilities: [
      "View Kota",
      "Kolam Renang",
      "Taman Bermain",
      "Area Jogging",
      "Security 24 Jam",
      "Parkir Underground",
    ],
    media: [
      { type: "image", url: slide3 },
      { type: "image", url: slide4 },
      { type: "video", url: "https://www.youtube.com/embed/example3" },
    ],
  },
  {
    title: "Taman Melati Asri",
    location: "Jl. Melati Raya No. 56, Depok",
    image: slide4,
    description:
      "Perumahan dengan konsep keluarga, lingkungan yang rindang dan asri. Cocok untuk keluarga yang menyukai ketenangan.",
    type: "Tipe 30/60",
    landSize: "60 m²",
    bedrooms: 2,
    bathrooms: 1,
    floors: 1,
    price: "Rp 350.000.000",
    dp: "Rp 35.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl: "https://www.google.com/maps/embed?pb=...",
    facilities: [
      "Taman Bermain",
      "Lapangan Bulutangkis",
      "Area Komunal",
      "Security Malam",
      "Parkir Motor",
    ],
    media: [
      { type: "image", url: slide4 },
      { type: "image", url: slide5 },
      { type: "video", url: "https://www.youtube.com/embed/example4" },
    ],
  },
  {
    title: "Grand Emerald City",
    location: "Jl. Emerald No. 99, Bekasi",
    image: slide5,
    description:
      "Kawasan perumahan modern dengan konsep kota mandiri. Lengkap dengan fasilitas komersial dan rekreasi dalam satu area.",
    type: "Tipe 70/140",
    landSize: "140 m²",
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    price: "Rp 1.250.000.000",
    dp: "Rp 125.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl: "https://www.google.com/maps/embed?pb=...",
    facilities: [
      "Mall Mini",
      "Kolam Renang Olimpiade",
      "Fitness Center",
      "Sekolah Internasional",
      "Hospital",
      "24 Jam Security",
    ],
    media: [
      { type: "image", url: slide5 },
      { type: "image", url: slide6 },
      { type: "video", url: "https://www.youtube.com/embed/example5" },
    ],
  },
  {
    title: "Riverside Garden",
    location: "Jl. Sungai Indah No. 33, Tangerang",
    image: slide6,
    description:
      "Perumahan dengan view sungai alami dan taman yang luas. Konsep back to nature dengan modernitas.",
    type: "Tipe 40/80",
    landSize: "80 m²",
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    price: "Rp 450.000.000",
    dp: "Rp 40.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl: "https://www.google.com/maps/embed?pb=...",
    facilities: [
      "View Sungai",
      "Taman Bermain",
      "Jogging Track",
      "Area Memancing",
      "Security 24 Jam",
    ],
    media: [
      { type: "image", url: slide6 },
      { type: "image", url: slide7 },
      { type: "video", url: "https://www.youtube.com/embed/example6" },
    ],
  },
  {
    title: "Metropolitan View",
    location: "Jl. Metropolitan No. 88, Jakarta Utara",
    image: slide7,
    description:
      "Apartemen dan townhouse dengan view kota metropolitan. Fasilitas lengkap dan akses strategis ke pusat kota.",
    type: "Tipe 50/100",
    landSize: "100 m²",
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    price: "Rp 650.000.000",
    dp: "Rp 60.000.000",
    certificate: "SHM",
    imb: "Ada",
    contact: "+62811710890",
    mapUrl: "https://www.google.com/maps/embed?pb=...",
    facilities: [
      "Rooftop Garden",
      "Gym",
      "Swimming Pool",
      "Playground",
      "24 Jam Security",
      "Parkir Basement",
    ],
    media: [
      { type: "image", url: slide7 },
      { type: "image", url: slide1 },
      { type: "video", url: "https://www.youtube.com/embed/example7" },
    ],
  },
];
